In [2]:
import pandas as pd
import numpy as np

In [4]:
path = "../canada_fsa_climate_footprint.csv"

df = pd.read_csv(path, header=2, thousands=",")

df.head(5)

,FSA,Name / Area,Province / Territory,Lat,Lon,Nearest Major Airport,Airport IATA,Airport SL km,Dist Set A km\n(YVR+SFO),Dist Set B km\n(YYZ+JFK),...,D2 Name,D2 SL km,D2 Driving km,D2 Driving hrs,CO2e CDG kg,CO2e LHR kg,CO2e NRT kg,Set Airport 1\n(IATA),CO2e Set1 kg,CO2e Set2 kg
0,A0A,Southeastern Avalon Peninsula (Ferryland),Newfoundland and Labrador,47.2195,-53.1448,St. John's Intl,YYT,53.3,5298.4,1946.1,...,Gros Morne NL,432.0,711.31,10.1441,745.8,811.6,1878.9,YVR,1097.5,1241.7
1,A0B,Western Avalon Peninsula (Argentia),Newfoundland and Labrador,47.3270,-53.6609,St. John's Intl,YYT,75.6,5258.2,1909.9,...,Gros Morne NL,394.6,633.14,8.0713,745.8,811.6,1878.9,YVR,1097.5,1241.7
2,A0C,Bonavista Peninsula (Bonavista),Newfoundland and Labrador,48.3843,-53.9081,St. John's Intl,YYT,121.0,5197.7,1915.2,...,Gros Morne NL,312.7,512.28,6.7709,745.8,811.6,1878.9,YVR,1097.5,1241.7
3,A0E,Burin Peninsula (Marystown),Newfoundland and Labrador,47.5607,-54.7801,St. John's Intl,YYT,152.2,5171.1,1832.8,...,Gros Morne NL,315.9,661.48,8.8154,745.8,811.6,1878.9,YVR,1097.5,1241.7
4,A0G,Northeast Newfoundland (Lewisporte),Newfoundland and Labrador,48.8657,-54.7296,St. John's Intl,YYT,201.7,5122.8,1870.7,...,Corner Brook NL,235.6,463.40,7.5179,745.8,811.6,1878.9,YVR,1097.5,1241.7

In [17]:
df.head()
# df = df.drop(columns=["Lat", "Lon"])
# df = df.drop(columns="Airport SL km")

,FSA,Name / Area,Province / Territory,Nearest Major Airport,Airport IATA,Dist Set A km\n(YVR+SFO),Dist Set B km\n(YYZ+JFK),Further Set,D1 Name,D1 SL km,...,D2 Name,D2 SL km,D2 Driving km,D2 Driving hrs,CO2e CDG kg,CO2e LHR kg,CO2e NRT kg,Set Airport 1\n(IATA),CO2e Set1 kg,CO2e Set2 kg
0,A0A,Southeastern Avalon Peninsula (Ferryland),Newfoundland and Labrador,St. John's Intl,YYT,5298.4,1946.1,A,St. John's NL,50.0,...,Gros Morne NL,432.0,711.31,10.1441,745.8,811.6,1878.9,YVR,1097.5,1241.7
1,A0B,Western Avalon Peninsula (Argentia),Newfoundland and Labrador,St. John's Intl,YYT,5258.2,1909.9,A,St. John's NL,75.9,...,Gros Morne NL,394.6,633.14,8.0713,745.8,811.6,1878.9,YVR,1097.5,1241.7
2,A0C,Bonavista Peninsula (Bonavista),Newfoundland and Labrador,St. John's Intl,YYT,5197.7,1915.2,A,St. John's NL,127.6,...,Gros Morne NL,312.7,512.28,6.7709,745.8,811.6,1878.9,YVR,1097.5,1241.7
3,A0E,Burin Peninsula (Marystown),Newfoundland and Labrador,St. John's Intl,YYT,5171.1,1832.8,A,Cape Breton (Cabot Trail) NS,471.5,...,Gros Morne NL,315.9,661.48,8.8154,745.8,811.6,1878.9,YVR,1097.5,1241.7
4,A0G,Northeast Newfoundland (Lewisporte),Newfoundland and Labrador,St. John's Intl,YYT,5122.8,1870.7,A,St. John's NL,208.2,...,Corner Brook NL,235.6,463.40,7.5179,745.8,811.6,1878.9,YVR,1097.5,1241.7