In [2]:
import pandas as pd
import numpy as np

In [4]:
path = "../canada_fsa_climate_footprint.csv"

df = pd.read_csv(path, header=2, thousands=",")

df.head(5)

,FSA,Name / Area,Province / Territory,Lat,Lon,Nearest Major Airport,Airport IATA,Airport SL km,Dist Set A km\n(YVR+SFO),Dist Set B km\n(YYZ+JFK),...,D2 Name,D2 SL km,D2 Driving km,D2 Driving hrs,CO2e CDG kg,CO2e LHR kg,CO2e NRT kg,Set Airport 1\n(IATA),CO2e Set1 kg,CO2e Set2 kg
0,A0A,Southeastern Avalon Peninsula (Ferryland),Newfoundland and Labrador,47.2195,-53.1448,St. John's Intl,YYT,53.3,5298.4,1946.1,...,Gros Morne NL,432.0,711.31,10.1441,745.8,811.6,1878.9,YVR,1097.5,1241.7
1,A0B,Western Avalon Peninsula (Argentia),Newfoundland and Labrador,47.3270,-53.6609,St. John's Intl,YYT,75.6,5258.2,1909.9,...,Gros Morne NL,394.6,633.14,8.0713,745.8,811.6,1878.9,YVR,1097.5,1241.7
2,A0C,Bonavista Peninsula (Bonavista),Newfoundland and Labrador,48.3843,-53.9081,St. John's Intl,YYT,121.0,5197.7,1915.2,...,Gros Morne NL,312.7,512.28,6.7709,745.8,811.6,1878.9,YVR,1097.5,1241.7
3,A0E,Burin Peninsula (Marystown),Newfoundland and Labrador,47.5607,-54.7801,St. John's Intl,YYT,152.2,5171.1,1832.8,...,Gros Morne NL,315.9,661.48,8.8154,745.8,811.6,1878.9,YVR,1097.5,1241.7
4,A0G,Northeast Newfoundland (Lewisporte),Newfoundland and Labrador,48.8657,-54.7296,St. John's Intl,YYT,201.7,5122.8,1870.7,...,Corner Brook NL,235.6,463.40,7.5179,745.8,811.6,1878.9,YVR,1097.5,1241.7

In [17]:
df.head()
# df = df.drop(columns=["Lat", "Lon"])
# df = df.drop(columns="Airport SL km")

,FSA,Name / Area,Province / Territory,Nearest Major Airport,Airport IATA,Dist Set A km\n(YVR+SFO),Dist Set B km\n(YYZ+JFK),Further Set,D1 Name,D1 SL km,...,D2 Name,D2 SL km,D2 Driving km,D2 Driving hrs,CO2e CDG kg,CO2e LHR kg,CO2e NRT kg,Set Airport 1\n(IATA),CO2e Set1 kg,CO2e Set2 kg
0,A0A,Southeastern Avalon Peninsula (Ferryland),Newfoundland and Labrador,St. John's Intl,YYT,5298.4,1946.1,A,St. John's NL,50.0,...,Gros Morne NL,432.0,711.31,10.1441,745.8,811.6,1878.9,YVR,1097.5,1241.7
1,A0B,Western Avalon Peninsula (Argentia),Newfoundland and Labrador,St. John's Intl,YYT,5258.2,1909.9,A,St. John's NL,75.9,...,Gros Morne NL,394.6,633.14,8.0713,745.8,811.6,1878.9,YVR,1097.5,1241.7
2,A0C,Bonavista Peninsula (Bonavista),Newfoundland and Labrador,St. John's Intl,YYT,5197.7,1915.2,A,St. John's NL,127.6,...,Gros Morne NL,312.7,512.28,6.7709,745.8,811.6,1878.9,YVR,1097.5,1241.7
3,A0E,Burin Peninsula (Marystown),Newfoundland and Labrador,St. John's Intl,YYT,5171.1,1832.8,A,Cape Breton (Cabot Trail) NS,471.5,...,Gros Morne NL,315.9,661.48,8.8154,745.8,811.6,1878.9,YVR,1097.5,1241.7
4,A0G,Northeast Newfoundland (Lewisporte),Newfoundland and Labrador,St. John's Intl,YYT,5122.8,1870.7,A,St. John's NL,208.2,...,Corner Brook NL,235.6,463.40,7.5179,745.8,811.6,1878.9,YVR,1097.5,1241.7

## Nearest airport city

Map each `airport_iata` to the city its airport serves. Keyed on IATA rather than the
airport name, since the names follow no consistent pattern ("Edmonton Intl" vs
"Sault Ste. Marie Airport" vs "Greater Moncton Romeo LeBlanc Intl").

In [ ]:
clean_path = "../canada_fsa_climate_footprint_clean.csv"
clean = pd.read_csv(clean_path)

# IATA -> city the airport serves. Where the airport's legal municipality differs from
# the city it serves, this takes the city served: YVR sits in Richmond, YYZ in Mississauga,
# and Bagotville is a borough of Saguenay.
AIRPORT_CITY = {
    "YAM": "Sault Ste. Marie",
    "YAT": "Attawapiskat",
    "YBC": "Baie-Comeau",
    "YBG": "Saguenay",
    "YBR": "Brandon",
    "YCB": "Cambridge Bay",
    "YCD": "Nanaimo",
    "YDF": "Deer Lake",
    "YEG": "Edmonton",
    "YFC": "Fredericton",
    "YGL": "Radisson",
    "YGR": "Îles-de-la-Madeleine",
    "YHO": "Hopedale",
    "YHZ": "Halifax",
    "YLW": "Kelowna",
    "YMM": "Fort McMurray",
    "YMX": "Mirabel",
    "YOW": "Ottawa",
    "YPL": "Pickle Lake",
    "YPR": "Prince Rupert",
    "YPX": "Puvirnituq",
    "YQB": "Quebec City",
    "YQL": "Lethbridge",
    "YQM": "Moncton",
    "YQR": "Regina",
    "YQT": "Thunder Bay",
    "YQU": "Grande Prairie",
    "YRB": "Resolute",
    "YSB": "Sudbury",
    "YTH": "Thompson",
    "YUL": "Montréal",
    "YVQ": "Norman Wells",
    "YVR": "Vancouver",
    "YWG": "Winnipeg",
    "YXE": "Saskatoon",
    "YXH": "Medicine Hat",
    "YXJ": "Fort St. John",
    "YXS": "Prince George",
    "YXU": "London",
    "YXY": "Whitehorse",
    "YYC": "Calgary",
    "YYD": "Smithers",
    "YYT": "St. John's",
    "YYZ": "Toronto",
    "YZF": "Yellowknife",
    "YZV": "Sept-Îles",
}

missing = set(clean["airport_iata"]) - set(AIRPORT_CITY)
assert not missing, f"unmapped IATA codes: {sorted(missing)}"

clean["nearest_airport_city"] = clean["airport_iata"].map(AIRPORT_CITY)
assert clean["nearest_airport_city"].notna().all()

clean.to_csv(clean_path, index=False)
clean[["fsa", "nearest_major_airport", "airport_iata", "nearest_airport_city"]].head()

## CO2 emissions cost

Price each FSA's five round-trip footprints under all six carbon tax regimes.

The tax values are **$/tonne** CO2 while the footprints are in **kg**, so each cost is
`(co2e_kg / 1000) * tax`, rounded to two significant figures. The CAD figures in the
parameters file already have the 1.4 exchange rate baked in — don't apply it again.

In [ ]:
from math import log10, floor


def round_sig(x, sig=2):
    if x == 0:
        return 0
    return round(x, sig - int(floor(log10(abs(x)))) - 1)


# Row 2 of the parameters file holds the rates; everything below it is reference notes.
taxes = pd.read_csv(
    "../footprint_parameters_June_16 pm(Tax Regimes).csv",
    encoding="utf-8-sig",
    nrows=1,
    usecols=range(6),
).iloc[0]

ROUTES = {
    "cdg": "co2e_cdg_kg",
    "lhr": "co2e_lhr_kg",
    "nrt": "co2e_nrt_kg",
    "set1": "co2e_set1_kg",
    "set2": "co2e_set2_kg",
}

co2 = clean[
    ["fsa", "name_/_area", "rovince_/_territory", "nearest_airport_city", *ROUTES.values()]
].copy()

for regime, rate in taxes.items():  # US_1..US_3 in USD, CAD_1..CAD_3 in CAD
    for route, kg_col in ROUTES.items():
        tonnes = clean[kg_col] / 1000
        co2[f"{regime.lower().replace('_', '')}_{route}"] = (tonnes * rate).map(round_sig)

co2.to_csv("../co2_emissions.csv", index=False)
print(taxes.to_dict())
co2.head()